### ISSUE TITLE
Error:(45) *** Android NDK: Aborting    .  Stop.

### ISSUE THREAD

**Issue by aviontechnology** [matthewn4444/VPlayer_lib#8]
Hello,

I am trying to build this project on 
ndk:- 14b
sdk:-  25
build:gradle:-1.3.0

then i get NDK aborting error.
Please check below error and give me solution.

Information:Gradle tasks [:VPlayerExample:generateDebugSources, :VPlayerExample:generateDebugAndroidTestSources, :VPlayerExample:mockableAndroidJar, :VPlayerExample:prepareDebugUnitTestDependencies, :VPlayer_library:generateDebugSources, :VPlayer_library:mockableAndroidJar, :VPlayer_library:prepareDebugUnitTestDependencies, :VPlayer_library:generateDebugAndroidTestSources]

/var/Kiran/SDKUbantu/Sdk/ndk-bundle/build/core/prebuilt-library.mk
Error:(45) *** Android NDK: Aborting    .  Stop.

Error:Execution failed for task ':VPlayer_library:ndkBuild'.
> Process 'command '/var/Kiran/SDKUbantu/Sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

**Comment by matthewn4444** [comment]
I will take a look... Are you running this on Linux?

**Comment by aviontechnology** [comment]
yes, my development environment is ubuntu 14.04 ,Android studio 2.2.3 java 1.8.
Please reply if you found any solution for this.

**Comment by skydsai** [comment]
I have the same problem  @aviontechnology , how to fix @matthewn4444

**Comment by spysoos** [comment]
I have the same problem @aviontechnology , but on windows 10

**Comment by matthewn4444** [comment]
I'm currently fixing the Android studio build side, hope to update with 64bit build soon.

**Comment by matthewn4444** [comment]
Just updated a change https://github.com/matthewn4444/VPlayer_lib/commit/1898b4b4b6079b4ef165da7f8e33db275800dd5d

Works for all arch (arm, arm7, arm8 64, x86, x86 64, mips) and you can build each of them into an apk with the library or the provided example using newer versions of gradle and highest version of NDK and Android Studio. Updates to sdk version will come soon (issues with "has text relocations" past sdk 22 will be fixed in a week or 2).

Closing for now.
